# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  # Step 1: Install Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  # Step 2: Install dependencies and build
  - script: |
      npm install
      npm run build
    displayName: 'Install dependencies and build application'

  # Step 3: Copy necessary files to artifact staging directory
  - task: CopyFiles@2
    inputs:
  #    SourceFolder: $(System.DefaultWorkingDirectory)
      Contents: |
        server/**          # Server-side code
        public/**          # Static assets and bundled output (bundle.js)
        # package.json       # Required for npm start in production
        # package-lock.json  # Lock file for reproducible installs
      TargetFolder: $(Build.ArtifactStagingDirectory)
    displayName: 'Copy necessary files to artifact staging directory'

  # Step 4: Publish the artifact
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: release
      publishLocation: 'Container'
    displayName: 'Publish build artifact'
